name = "browserleaks-io"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_API_URL = "https://api.browserleaks.io/v1"
